### ISSUE TITLE
[SUGGESTION] Offline Player Stop Working

### ISSUE THREAD

**Issue by kacperleague9** [JadssDev/JadGens#1]
So my suggestion is a config value that allows for the plugin to stop generating when user is offline
should support superiorskyblock with [api](https://www.spigotmc.org/resources/superiorskyblockapi-api-for-superiorskyblock2.64555/) so that when only one member of island is online all generators on island are working
of course afk support for essentials would be nice

**Comment by JadssDev** [comment]
Being done.

**Comment by JadssDev** [comment]
Done!
